# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfaae3ef168110d1eb775917a879346052dd52f99c31c4658460f0beec27ce91e0de053e3564527e16b5dc0d3e05580255ae1b96208f3594614092c25a21c6bc

test:
  secret_key_base: 30608d0bcb4f7893eb2e47fd7e436c96d229e9501f8f72d89a41b76995561d39eb753bd8904a163c8c37b1b54e3dcf6c16a7ed9a4f445120caba1a98090e8f27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
